import { createAdministratorApiClient } from "@sarmg/admin-web";
import { isErrorEnvelope, type ErrorEnvelope } from "@sarmg/contracts";
import { isApiClientError } from "@sarmg/http-client";
export const CURRENT_API_PREFIX = "/api/v2";
export const adminApi = createAdministratorApiClient();
export type Snapshot = {revision:string;sunshine_version:string;fields:Record<string,string>;effectiveness:"pending_verification"|"awaiting_restart"};
export type DeviceInfo = {id:string;name:string;registered:boolean;pairing_pending:boolean;revoked:boolean;client_online:boolean;sunshine_reachable:boolean|null;configuration_state:string;snapshot:Snapshot|null;capabilities:{protocol:string;client_version:string;os:string;sunshine_version:string;restart_allowed:boolean;managed_fields:string[]}|null;last_seen_at_micros:number|null};
export type Ticket={device:DeviceInfo;manager_id:string;token:string};
export type ClientAuthorization={authorization_code:string};
export type ConfigFieldDefinition={key:string;kind:"text"|"integer"|"boolean"|"select";minimum?:number;maximum?:number;maximum_length?:number;options?:string[];requires_restart:boolean;supported_sunshine_versions:string[];operating_systems:string[];prerequisite?:string};
export type Command={kind:"read_config"}|{kind:"patch_config";expected_revision:string;set:Record<string,string|number|boolean>;remove:string[];restart_policy:"manual"}|{kind:"restart";expected_revision:string;administrator_confirmed:true};
export type Report={kind:string;snapshot?:Snapshot;reason?:string;actual_revision?:string};
export type Operation={operation_id:string;device_id:string;action:string;state:"pending"|"running"|"succeeded"|"failed"|"unknown"|"dead_letter"|"resolved";attempt:number;created_at_micros:number;updated_at_micros:number;result:Report|null;reconciliation:Report|null;resolution:string|null};
export function record(value:unknown):value is Record<string,unknown>{return typeof value==="object"&&value!==null&&!Array.isArray(value)}
export function isSnapshot(value:unknown):value is Snapshot{return record(value)&&typeof value.revision==="string"&&/^[a-f0-9]{64}$/.test(value.revision)&&typeof value.sunshine_version==="string"&&record(value.fields)&&Object.values(value.fields).every(field=>typeof field==="string")&&(value.effectiveness==="pending_verification"||value.effectiveness==="awaiting_restart")}
export function isDevice(value:unknown):value is DeviceInfo{
 return record(value)&&typeof value.id==="string"&&typeof value.name==="string"&&typeof value.registered==="boolean"&&typeof value.pairing_pending==="boolean"&&typeof value.revoked==="boolean"&&typeof value.client_online==="boolean"&&(value.sunshine_reachable===null||typeof value.sunshine_reachable==="boolean")&&typeof value.configuration_state==="string"&&(value.snapshot===null||isSnapshot(value.snapshot))&&(value.capabilities===null||(record(value.capabilities)&&typeof value.capabilities.protocol==="string"&&typeof value.capabilities.client_version==="string"&&typeof value.capabilities.os==="string"&&typeof value.capabilities.sunshine_version==="string"&&typeof value.capabilities.restart_allowed==="boolean"&&Array.isArray(value.capabilities.managed_fields)&&value.capabilities.managed_fields.every(field=>typeof field==="string")))&&(value.last_seen_at_micros===null||Number.isSafeInteger(value.last_seen_at_micros));
}
export function isDevices(value:unknown):value is DeviceInfo[]{return Array.isArray(value)&&value.every(isDevice)}
export function isTicket(value:unknown):value is Ticket{return record(value)&&isDevice(value.device)&&typeof value.manager_id==="string"&&typeof value.token==="string"}
export function isClientAuthorization(value:unknown):value is ClientAuthorization{return record(value)&&Object.keys(value).length===1&&typeof value.authorization_code==="string"&&/^[a-f0-9]{64}$/.test(value.authorization_code)}
export function isConfigFieldDefinition(value:unknown):value is ConfigFieldDefinition{return record(value)&&typeof value.key==="string"&&["text","integer","boolean","select"].includes(String(value.kind))&&(!("minimum" in value)||Number.isSafeInteger(value.minimum))&&(!("maximum" in value)||Number.isSafeInteger(value.maximum))&&(!("maximum_length" in value)||Number.isSafeInteger(value.maximum_length))&&(!("options" in value)||(Array.isArray(value.options)&&value.options.every(option=>typeof option==="string")))&&typeof value.requires_restart==="boolean"&&Array.isArray(value.supported_sunshine_versions)&&value.supported_sunshine_versions.every(version=>typeof version==="string")&&Array.isArray(value.operating_systems)&&value.operating_systems.every(os=>typeof os==="string")&&(!("prerequisite" in value)||typeof value.prerequisite==="string")}
export function isConfigFieldDefinitions(value:unknown):value is ConfigFieldDefinition[]{return Array.isArray(value)&&value.every(isConfigFieldDefinition)&&new Set(value.map(field=>field.key)).size===value.length}
function isReport(value:unknown):value is Report{return record(value)&&typeof value.kind==="string"&&(!("snapshot" in value)||isSnapshot(value.snapshot))}
export function isOperation(value:unknown):value is Operation{return record(value)&&typeof value.operation_id==="string"&&typeof value.device_id==="string"&&typeof value.action==="string"&&typeof value.state==="string"&&["pending","running","succeeded","failed","unknown","dead_letter","resolved"].includes(value.state)&&Number.isSafeInteger(value.attempt)&&Number.isSafeInteger(value.created_at_micros)&&Number.isSafeInteger(value.updated_at_micros)&&(value.result===null||isReport(value.result))&&(value.reconciliation===null||isReport(value.reconciliation))&&(value.resolution===null||typeof value.resolution==="string")}
export function isOperations(value:unknown):value is Operation[]{return Array.isArray(value)&&value.every(isOperation)}
export function currentErrorEnvelope(error:unknown):ErrorEnvelope|undefined{if(!isApiClientError(error))return undefined;return isErrorEnvelope(error.envelope)?error.envelope:undefined}
