import { operationLabel, configValueLabel } from "./display-labels";
import { t } from "../shell/i18n.js";
import { InstanceNameField } from "../shell/index.js";
import {useEffect,useState,type FormEvent} from "react";
import {Button,ConfirmDangerDialog,ErrorState,FormField,TextField} from "@sarmg/admin-ui";
import {useAdminApplication,errorRequestId} from "../shell/index.js";
import {CURRENT_API_PREFIX,isDevice,isOperation,isOperations,type Command,type DeviceInfo,type Operation,type Snapshot,type Ticket,currentErrorEnvelope} from "./api";
import {configFields} from "./config-fields";
import {TicketPanel} from "./DeviceRegistrationDialog";
const states:Record<string,string>={unknown:t("尚未核对", "Not yet checked"),awaiting_restart:t("配置已保存，等待管理员重启", "Configuration saved; waiting for an administrator to restart"),pending_verification:t("配置已读取，运行时生效待验证", "Configuration read; runtime effect needs verification"),drift_detected:t("实际配置与已保存修订不同，请核对冲突", "Actual configuration differs from the saved revision; review the conflict")};
const tasks:Record<string,string>={pending:t("排队中", "Queued"),running:t("执行中", "Running"),succeeded:t("执行已完成", "Execution completed"),failed:t("执行失败", "Execution failed"),unknown:t("结果不确定", "Outcome unknown"),resolved:t("已人工核对", "Manually reconciled"),dead_letter:t("执行已拒绝", "Execution rejected")};
export function ClientWorkspace({device,changed,ticket:initialTicket,page}:{device:DeviceInfo;changed():void;ticket:Ticket|null;page:string}){
 const{client,notify}=useAdminApplication();const[ticket,setTicket]=useState(initialTicket);const[operations,setOperations]=useState<Operation[]>([]);
 const[busy,setBusy]=useState(false);const[failure,setFailure]=useState<{message:string;requestId?:string}|null>(null);const[confirm,setConfirm]=useState<{title:string;description:string;run():Promise<void>}|null>(null);
 const[baseline,setBaseline]=useState<Snapshot|null>(device.snapshot);const[draft,setDraft]=useState<Record<string,string>>(device.snapshot?.fields??{});const[remove,setRemove]=useState<string[]>([]);const[preview,setPreview]=useState<Command|null>(null);
 const base=`${CURRENT_API_PREFIX}/sunshine/devices/${device.id}`;
 useEffect(()=>{if(!baseline&&device.snapshot){setBaseline(device.snapshot);setDraft(device.snapshot.fields)}},[baseline,device.snapshot]);
 useEffect(()=>{setTicket(initialTicket)},[initialTicket]);
 useEffect(()=>{const controller=new AbortController();let active=true;async function load(){try{const values=await client.request(base+"/tasks",isOperations,{signal:controller.signal});if(active)setOperations(values)}catch(error){if(active)setFailure({message:t("任务列表暂时不可用", "The task list is temporarily unavailable"),requestId:errorRequestId(error)})}}
 void load();const timer=setInterval(()=>void load(),2000);return()=>{active=false;controller.abort();clearInterval(timer)}},[base,client]);
 async function perform(action:()=>Promise<void>){if(busy)return;setBusy(true);setFailure(null);try{await action();changed()}catch(error){setFailure({message:currentErrorEnvelope(error)?.code==="conflict"?t("配置或设备状态发生冲突，请刷新后核对。", "Configuration or device state conflict. Refresh and review the latest state."):t("操作未能确认，请检查任务记录，勿直接重复重启。", "The operation could not be confirmed. Check task history; do not blindly repeat a restart."),requestId:errorRequestId(error)})}finally{setBusy(false)}}
 async function submit(command:Command){await perform(async()=>{const operation=await client.request(base+"/tasks",isOperation,{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify(command)});setOperations(values=>[operation,...values.filter(value=>value.operation_id!==operation.operation_id)]);notify(t("任务已持久化，等待 客户端 执行。", "Task persisted; waiting for the client to execute it."));setPreview(null)})}
 const blocked=busy||device.revoked||!device.registered||operations.some(operation=>["pending","running","unknown"].includes(operation.state));
 function difference(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!baseline)return;const set:Record<string,string|number|boolean>={};for(const field of configFields){const value=draft[field.key]??"";if(!remove.includes(field.key)&&value!==""&&value!==baseline.fields[field.key]){set[field.key]=field.kind==="integer"?Number(value):field.boolean?value==="true":value}}
 const deleted=remove.filter(key=>key in baseline.fields);if(!Object.keys(set).length&&!deleted.length){notify(t("没有需要保存的变更", "No changes to save"));return}setPreview({kind:"patch_config",expected_revision:baseline.revision,set,remove:deleted,restart_policy:"manual"})}
 function loadLatest(){if(device.snapshot){setBaseline(device.snapshot);setDraft(device.snapshot.fields);setRemove([]);setPreview(null)}}
 return <div className="sarmg-instance-detail sunshine-workspace" aria-busy={busy}>
 {failure&&<ErrorState requestId={failure.requestId}>{failure.message}</ErrorState>}
 {page===t("设备状态", "Device status")&&<section className="sarmg-content-panel"><h2>{t("设备状态", "Device status")}</h2><dl><dt>{t("客户端", "Client")}</dt><dd>{device.revoked?t("凭据已撤销", "Credentials revoked"):!device.registered?(device.pairing_pending?t("等待配对", "Waiting for pairing"):t("配对已取消", "Pairing cancelled")):device.client_online?t("在线", "Online"):t("离线", "Offline")}</dd><dt>{t("Sunshine 接口", "Sunshine API")}</dt><dd>{device.sunshine_reachable===null?t("未知", "Unknown"):device.sunshine_reachable?t("可访问", "Reachable"):t("不可访问", "Unreachable")}</dd><dt>{t("配置状态", "Configuration status")}</dt><dd>{states[device.configuration_state]??t("未知", "Unknown")}</dd></dl>
 <p>{t("客户端 在线不等于 Sunshine 正常；配置保存或重启响应不证明运行时已生效。", "An online client does not mean Sunshine is healthy. Saving or restarting does not prove runtime effect.")}</p>
 <form onSubmit={event=>{event.preventDefault();const name=String(new FormData(event.currentTarget).get("name")??"").trim();void perform(async()=>{await client.request(base,isDevice,{method:"PATCH",body:JSON.stringify({name})})})}}><FormField label={t("实例名称", "Instance name")}><InstanceNameField key={device.name} name="name" defaultValue={device.name} required  /></FormField><Button type="submit" disabled={busy}>{t("保存名称", "Save name")}</Button></form>
 {device.pairing_pending&&!device.registered&&!device.revoked&&<Button disabled={busy} onClick={()=>setConfirm({title:t("取消配对", "Cancel pairing"),description:t("配对码将立即失效。实例记录会保留；如需重新配对，请新建实例。", "The pairing code will stop working immediately. The instance remains; create a new instance to pair again."),run:()=>perform(async()=>{await client.request(base+"/pairing",(value):value is undefined=>value===undefined,{method:"DELETE"});setTicket(null)})})}>{t("取消配对", "Cancel pairing")}</Button>}
 {device.registered&&!device.revoked&&<Button disabled={busy} onClick={()=>setConfirm({title:t("撤销设备凭据", "Revoke device credentials"),description:t("将断开 客户端 并永久禁止该设备凭据。执行中的任务可能变为不确定；如需重新注册，请新建设备。", "This disconnects the client and permanently revokes its credentials. Running tasks may have an unknown outcome. Create a new device to register again."),run:()=>perform(async()=>{await client.request(base+"/revoke",(value):value is undefined=>value===undefined,{method:"POST"});setTicket(null)})})}>{t("撤销设备凭据", "Revoke device credentials")}</Button>}
 {ticket&&device.pairing_pending&&!device.registered&&!device.revoked&&<TicketPanel ticket={ticket}/>}</section>}
 {page===t("Sunshine 配置", "Sunshine configuration")&&<section className="sarmg-content-panel"><h2>{t("Sunshine 配置", "Sunshine configuration")}</h2><p>{t("受管字段由 管理端 统一管理。本地同时编辑可能发生竞争；修订检查不是 Sunshine 原子并发控制。", "The manager owns managed fields. Local edits may race with remote changes; revision checks are not atomic concurrency control in Sunshine.")}</p>
 <div className="sarmg-actions"><Button disabled={blocked} onClick={()=>void submit({kind:"read_config"})}>{t("从 客户端 读取配置", "Read configuration from client")}</Button><Button disabled={!device.snapshot||busy} onClick={loadLatest}>{t("使用最新配置（丢弃未提交编辑）", "Use latest configuration (discard unsaved edits)")}</Button></div>
 {baseline&&device.snapshot&&baseline.revision!==device.snapshot.revision&&<p role="alert">{t("配置修订已变化。请核对最新配置后重新编辑，不能覆盖其他修改。", "The configuration revision has changed. Review the latest configuration and edit again; do not overwrite other changes.")}</p>}
 {baseline?<form onSubmit={difference}><p>{t("未列出的配置保留不变；命令、文件路径和敏感网络设置不开放远程修改。", "Unlisted settings are preserved. Commands, file paths and sensitive network settings cannot be changed remotely.")}</p>
 {configFields.map(field=><div key={field.key} className="sunshine-config-field"><FormField label={field.label}>{field.kind==="select"?<select aria-label={field.label} value={draft[field.key]??""} disabled={busy||remove.includes(field.key)} onChange={event=>setDraft({...draft,[field.key]:event.target.value})}><option value="">{t("未显式设置", "Not explicitly set")}</option>{field.options?.map(value=><option key={value} value={value}>{configValueLabel(value)}</option>)}</select>:<TextField type={field.kind==="integer"?"number":"text"} min={field.min} max={field.max} step={1} maxLength={field.kind==="text"?64:undefined} pattern={field.kind==="text"?".{1,32}":undefined} value={draft[field.key]??""} disabled={busy||remove.includes(field.key)} onChange={event=>setDraft({...draft,[field.key]:event.target.value})}/>}</FormField>
 <label><input type="checkbox" checked={remove.includes(field.key)} disabled={busy||!(field.key in baseline.fields)} onChange={event=>setRemove(event.target.checked?[...remove,field.key]:remove.filter(key=>key!==field.key))}/>{t("恢复默认（删除显式设置）", "Restore default (remove explicit setting)")}</label></div>)}
 <Button type="submit" disabled={blocked}>{t("预览变更", "Preview changes")}</Button></form>:<p>{t("尚未读取配置。设备注册后可提交读取任务；离线任务会等待连接。", "Configuration has not been read. Submit a read task after registration; offline tasks wait for a connection.")}</p>}
 {preview?.kind==="patch_config"&&<section className="sarmg-content-stack" aria-label={t("变更差异预览", "Change preview")}><h3>{t("变更差异预览", "Change preview")}</h3><table><thead><tr><th>{t("字段", "Field")}</th><th>{t("原值", "Previous value")}</th><th>{t("新值", "New value")}</th></tr></thead><tbody>{[...Object.keys(preview.set),...preview.remove].map(key=><tr key={key}><td>{configFields.find(field=>field.key===key)?.label??key}</td><td>{baseline?.fields[key]===undefined?t("默认", "Default"):configValueLabel(baseline.fields[key])}</td><td>{preview.remove.includes(key)?t("恢复默认", "Restore default"):configValueLabel(String(preview.set[key]))}</td></tr>)}</tbody></table><p>{t("只保存配置，不自动重启。", "Save configuration only; do not restart automatically.")}</p><Button disabled={blocked} onClick={()=>void submit(preview)}>{t("确认保存配置", "Confirm configuration save")}</Button><Button onClick={()=>setPreview(null)}>{t("返回编辑", "Back to editing")}</Button></section>}
 <p>{states[device.configuration_state]}</p><Button disabled={blocked||!device.snapshot||!device.capabilities?.restart_allowed} onClick={()=>setConfirm({title:t("确认重启 Sunshine", "Confirm Sunshine restart"),description:t("重启可能中断正在进行的串流。必须由管理员明确授权；客户端 管理进程保持独立。重启后仍可能需要人工验证运行时生效。", "Restarting may interrupt an active stream and requires explicit administrator authorization. The client remains independent. Runtime effect may still need manual verification after restarting."),run:async()=>{if(device.snapshot)await submit({kind:"restart",expected_revision:device.snapshot.revision,administrator_confirmed:true})}})}>{t("重启 Sunshine", "Restart Sunshine")}</Button>{!device.capabilities?.restart_allowed&&<p>{t("客户端 本机尚未授权受控重启。", "Controlled restarts have not been authorized locally on the client.")}</p>}</section>}
 {page===t("任务记录", "Task history")&&<section className="sarmg-content-panel"><h2>{t("任务记录", "Task history")}</h2>{!operations.length&&<p>{t("暂无任务", "No tasks yet")}</p>}{operations.map(operation=><article className="sarmg-content-stack" key={operation.operation_id}><h3>{operationLabel(operation.action)} · {tasks[operation.state]}</h3><code>{operation.operation_id}</code>{operation.result&&<p>{t("结果：", "Result:")}{operationLabel(operation.result.kind)} {operation.result.reason?operationLabel(operation.result.reason):""}</p>}{operation.result?.kind==="conflict"&&<p role="alert">{t("配置冲突，请重新读取并核对差异。", "Configuration conflict. Read the configuration again and review the differences.")}</p>}{operation.reconciliation&&<p>{t("客户端 核对证据：", "Client reconciliation evidence:")}{operationLabel(operation.reconciliation.kind)} {operation.reconciliation.reason?operationLabel(operation.reconciliation.reason):""}{t("。证据不会自动代替管理员确认。", ". Evidence does not replace administrator confirmation.")}</p>}{operation.state==="unknown"&&<div className="sarmg-actions">{[["confirmed_succeeded",t("确认已成功", "Confirm success")],["confirmed_failed",t("确认未成功", "Confirm failure")],["unable_to_confirm",t("仍无法确认", "Still unable to confirm")]].map(([resolution,label])=><Button key={resolution} disabled={busy} onClick={()=>setConfirm({title:label,description:t("请先核对实际设备状态。此操作只记录人工结论，不会重跑任务。", "Check the actual device state first. This records a manual conclusion only; it does not rerun the task."),run:()=>perform(async()=>{const updated=await client.request(`${CURRENT_API_PREFIX}/sunshine/operations/${operation.operation_id}/resolve`,isOperation,{method:"POST",body:JSON.stringify({resolution})});setOperations(values=>values.map(value=>value.operation_id===updated.operation_id?updated:value))})})}>{label}</Button>)}</div>}</article>)}</section>}
 {confirm&&<ConfirmDangerDialog title={confirm.title} description={confirm.description} pending={busy} onClose={()=>setConfirm(null)} onConfirm={()=>{const action=confirm;setConfirm(null);void action.run()}}/>}
 </div>;
}
