import { operationLabel, configValueLabel } from "./display-labels";
import { t } from "@sarmg/admin-ui/i18n";
import { InstanceNameField } from "@sarmg/admin-shell";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {Button,ConfirmDangerDialog,ErrorState,FormField,TextField} from "@sarmg/admin-ui";
import {useAdminApplication,errorRequestId} from "@sarmg/admin-shell";
import {CURRENT_API_PREFIX,isClientAuthorization,isDevice,isOperation,isOperations,type ClientAuthorization,type Command,type ConfigFieldDefinition,type DeviceInfo,type Operation,type Snapshot,type Ticket,currentErrorEnvelope} from "./api";
import {configCategories,fieldsForDevice,prerequisiteLabel,type ConfigCategory} from "./config-fields";
import {SunshineControls} from "./SunshineControls";
const states:Record<string,string>={unknown:t("尚未核对", "Not yet checked"),awaiting_restart:t("配置已保存，等待管理员重启", "Configuration saved; waiting for an administrator to restart"),pending_verification:t("配置已读取，运行时生效待验证", "Configuration read; runtime effect needs verification"),drift_detected:t("实际配置与已保存修订不同，请核对冲突", "Actual configuration differs from the saved revision; review the conflict")};
const tasks:Record<string,string>={pending:t("排队中", "Queued"),running:t("执行中", "Running"),succeeded:t("执行已完成", "Execution completed"),failed:t("执行失败", "Execution failed"),unknown:t("结果不确定", "Outcome unknown"),resolved:t("已人工核对", "Manually reconciled"),dead_letter:t("执行已拒绝", "Execution rejected")};
type WorkspaceFailure={message:string;requestId?:string};
export function ClientWorkspace({device,fieldDefinitions,refreshSignal,changed,removed,ticket:initialTicket,page}:{device:DeviceInfo;fieldDefinitions:ConfigFieldDefinition[]|null;refreshSignal:number;changed():void;removed():void;ticket:Ticket|null;page:"details"|"logs"}){
 const{client,notify}=useAdminApplication();const[operations,setOperations]=useState<Operation[]>([]);
 const[authorization,setAuthorization]=useState<ClientAuthorization|null>(initialTicket?{manager_id:initialTicket.manager_id,device_id:initialTicket.device.id,authorization_code:initialTicket.token}:null);
 const[busy,setBusy]=useState(false);const[authorizationFailure,setAuthorizationFailure]=useState<WorkspaceFailure|null>(null);const[taskFailure,setTaskFailure]=useState<WorkspaceFailure|null>(null);const[actionFailure,setActionFailure]=useState<WorkspaceFailure|null>(null);const[confirm,setConfirm]=useState<{title:string;description:string;run():Promise<void>}|null>(null);
 const[name,setName]=useState(device.name);const persistedName=useRef(device.name);
 const[baseline,setBaseline]=useState<Snapshot|null>(device.snapshot);const[draft,setDraft]=useState<Record<string,string>>(device.snapshot?.fields??{});const[remove,setRemove]=useState<string[]>([]);const[preview,setPreview]=useState<Command|null>(null);
 const idempotencyKeys=useRef(new Map<string,string>());const operationRevision=useRef(0);
 const[configCategory,setConfigCategory]=useState<ConfigCategory>("general");
 const configFields=fieldsForDevice(fieldDefinitions??[],device);
 const visibleCategories=configCategories.filter(category=>!("encoder" in category)||configFields.some(field=>field.category===category.id));
 const activeCategory=visibleCategories.some(category=>category.id===configCategory)?configCategory:"general";
 const base=`${CURRENT_API_PREFIX}/sunshine/devices/${device.id}`;
 useEffect(()=>{if(!baseline&&device.snapshot){setBaseline(device.snapshot);setDraft(device.snapshot.fields)}},[baseline,device.snapshot]);
 useEffect(()=>{
  const previous=persistedName.current;persistedName.current=device.name;
  // Refresh clean fields without replacing an administrator's unsaved draft.
  setName(current=>current===previous?device.name:current);
 },[device.name]);
 useEffect(()=>{const controller=new AbortController();let active=true;void client.request(base+"/authorization",isClientAuthorization,{signal:controller.signal}).then(value=>{if(active){setAuthorization(value);setAuthorizationFailure(null)}}).catch(error=>{if(active)setAuthorizationFailure({message:t("无法读取实例授权码", "Unable to load the instance authorization code"),requestId:errorRequestId(error)})});return()=>{active=false;controller.abort()}},[base,client,refreshSignal]);
 useEffect(()=>{const controller=new AbortController();let active=true;let timer:number|undefined;async function load(){const revision=operationRevision.current;try{const values=await client.request(base+"/tasks",isOperations,{signal:controller.signal});if(active&&revision===operationRevision.current){setOperations(values);setTaskFailure(null)}}catch(error){if(active)setTaskFailure({message:t("日志暂时不可用", "Logs are temporarily unavailable"),requestId:errorRequestId(error)})}finally{if(active)timer=window.setTimeout(load,2000)}}
 void load();return()=>{active=false;controller.abort();if(timer!==undefined)clearTimeout(timer)}},[base,client,refreshSignal]);
 async function perform(action:()=>Promise<void>,after:()=>void=changed){if(busy)return;setBusy(true);setActionFailure(null);try{await action();after()}catch(error){setActionFailure({message:currentErrorEnvelope(error)?.code==="conflict"?t("配置或设备状态发生冲突，请刷新后核对。", "Configuration or device state conflict. Refresh and review the latest state."):t("操作未能确认，请检查日志，勿直接重复重启。", "The operation could not be confirmed. Check the logs; do not blindly repeat a restart."),requestId:errorRequestId(error)})}finally{setBusy(false)}}
 function randomAuthorizationCode(){const alphabet="abcdefghijklmnopqrstuvwxyz0123456789";let result="";while(result.length<36){for(const value of crypto.getRandomValues(new Uint8Array(64))){if(value<252)result+=alphabet[value%alphabet.length];if(result.length===36)break}}return result}
 async function submit(command:Command){const body=JSON.stringify(command);const key=idempotencyKeys.current.get(body)??crypto.randomUUID();idempotencyKeys.current.set(body,key);await perform(async()=>{const operation=await client.request(base+"/tasks",isOperation,{method:"POST",headers:{"Idempotency-Key":key},body});idempotencyKeys.current.delete(body);operationRevision.current+=1;setOperations(values=>[operation,...values.filter(value=>value.operation_id!==operation.operation_id)]);notify(t("操作已写入日志，等待客户端执行。", "The operation was written to the log and is waiting for the client."));setPreview(null)})}
 const blocked=busy||device.revoked||!device.registered||operations.some(operation=>["pending","running","unknown"].includes(operation.state));
 function difference(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!baseline)return;
 // Reveal invalid fields before native validation tries to focus a hidden category.
 const invalid=event.currentTarget.querySelector<HTMLInputElement|HTMLSelectElement>("input:invalid, select:invalid");
 if(invalid){const category=invalid.closest<HTMLElement>("[data-config-category]")?.dataset.configCategory as ConfigCategory|undefined;if(category)setConfigCategory(category);requestAnimationFrame(()=>invalid.reportValidity());return}
 const set:Record<string,string|number|boolean>={};for(const field of configFields){const value=draft[field.key]??"";if(!remove.includes(field.key)&&value!==""&&value!==baseline.fields[field.key]){set[field.key]=field.kind==="integer"?Number(value):field.boolean?value==="true":value}}
 const deleted=remove.filter(key=>key in baseline.fields);if(!Object.keys(set).length&&!deleted.length){notify(t("没有需要保存的变更", "No changes to save"));return}setPreview({kind:"patch_config",expected_revision:baseline.revision,set,remove:deleted,restart_policy:"manual"})}
 function loadLatest(){if(device.snapshot){setBaseline(device.snapshot);setDraft(device.snapshot.fields);setRemove([]);setPreview(null)}}
 return <div className="sarmg-content-stack sunshine-workspace" aria-busy={busy}>
 {authorizationFailure&&<ErrorState requestId={authorizationFailure.requestId}>{authorizationFailure.message}</ErrorState>}
 {taskFailure&&<ErrorState requestId={taskFailure.requestId}>{taskFailure.message}</ErrorState>}
 {actionFailure&&<ErrorState requestId={actionFailure.requestId}>{actionFailure.message}</ErrorState>}
 {page==="details"&&<><section className="sarmg-content-panel" aria-label={t("配对账户信息", "Pairing account information")}><h2>{device.name}</h2><dl className="sunshine-detail-list"><dt>{t("账户名", "Account name")}</dt><dd>{device.name}</dd><dt>{t("账户", "Account")}</dt><dd><code>{authorization?.device_id??device.id}</code></dd><dt>{t("密码", "Password")}</dt><dd>{authorization?<code className="sunshine-token">{authorization.authorization_code}</code>:t("正在读取…", "Loading…")}</dd><dt>{t("配对状态", "Pairing status")}</dt><dd>{device.revoked?t("凭据已撤销", "Credentials revoked"):!device.registered?(device.pairing_pending?t("等待配对", "Waiting for pairing"):t("配对已取消", "Pairing cancelled")):t("已配对", "Paired")}</dd></dl></section>
 <section className="sarmg-content-panel" aria-label={t("实例设置", "Instance settings")}><h2>{t("实例设置", "Instance settings")}</h2><form onSubmit={event=>{event.preventDefault();void perform(async()=>{const updated=await client.request(base,isDevice,{method:"PATCH",body:JSON.stringify({name:name.trim()})});setName(updated.name);persistedName.current=updated.name;notify(t("实例名称已保存", "Instance name saved"))})}} aria-busy={busy}><FormField label={t("实例名称", "Instance name")}><InstanceNameField name="name" value={name} onChange={event=>setName(event.target.value)} required readOnly={busy}/></FormField><div className="sarmg-actions"><Button type="submit" disabled={busy||name.trim()===device.name}>{busy?t("正在保存…", "Saving…"):t("保存名称", "Save name")}</Button></div></form></section>
 <section className="sarmg-content-panel" aria-label={t("Sunshine 状态", "Sunshine status")}><h2>{t("Sunshine 状态", "Sunshine status")}</h2><dl className="sunshine-detail-list"><dt>{t("客户端", "Client")}</dt><dd>{device.client_online?t("在线", "Online"):t("离线", "Offline")}</dd><dt>{t("Sunshine 接口", "Sunshine API")}</dt><dd>{device.sunshine_reachable===null?t("未知", "Unknown"):device.sunshine_reachable?t("可访问", "Reachable"):t("不可访问", "Unreachable")}</dd><dt>{t("配置状态", "Configuration status")}</dt><dd>{states[device.configuration_state]??t("未知", "Unknown")}</dd></dl><p>{t("客户端 在线不等于 Sunshine 正常；配置保存或重启响应不证明运行时已生效。", "An online client does not mean Sunshine is healthy. Saving or restarting does not prove runtime effect.")}</p></section>
 <section className="sarmg-content-panel" aria-label={t("实例操作", "Instance actions")}><h2>{t("实例操作", "Instance actions")}</h2><p>{t("这是该实例的长期授权码，服务端会加密保存并允许之后查看或更换；更换后客户端必须重新配对。", "This is the instance's long-lived authorization code. The server stores it encrypted and keeps it available to view or change; changing it requires the client to pair again.")}</p><div className="sarmg-actions">{!device.revoked&&<Button disabled={busy} onClick={()=>setConfirm({title:t("更换密码", "Change password"),description:t("这会立即撤销当前客户端凭据。客户端必须使用新的授权码重新配对后才能连接。", "This immediately revokes the current client credential. The client must pair again with the new authorization code before it can reconnect."),run:()=>perform(async()=>{const value=await client.request(base+"/authorization",isClientAuthorization,{method:"PUT",body:JSON.stringify({authorization_code:randomAuthorizationCode()})});setAuthorization(value);notify(t("密码已更换，请在客户端使用新授权码重新配对。", "Password changed. Pair the client again with the new authorization code."))})})}>{t("更换密码", "Change password")}</Button>}
 {device.pairing_pending&&!device.registered&&!device.revoked&&<Button disabled={busy} onClick={()=>setConfirm({title:t("取消配对", "Cancel pairing"),description:t("当前授权码将停止配对；取消后可永久删除该实例，也可通过“更换密码”恢复。", "The current authorization code will stop pairing. Afterwards the instance can be deleted permanently or reactivated with Change password."),run:()=>perform(async()=>{await client.request(base+"/pairing",(value):value is undefined=>value===undefined,{method:"DELETE"})})})}>{t("取消配对", "Cancel pairing")}</Button>}
 {device.registered&&!device.revoked&&<Button disabled={busy} onClick={()=>setConfirm({title:t("撤销设备凭据", "Revoke device credentials"),description:t("将断开 客户端 并永久禁止该设备凭据。执行中的任务可能变为不确定；如需重新注册，请新建设备。", "This disconnects the client and permanently revokes its credentials. Running tasks may have an unknown outcome. Create a new device to register again."),run:()=>perform(async()=>{await client.request(base+"/revoke",(value):value is undefined=>value===undefined,{method:"POST"})})})}>{t("撤销设备凭据", "Revoke device credentials")}</Button>}
 <Button disabled={busy} onClick={()=>setConfirm({title:t("删除实例", "Delete instance"),description:t("永久删除该实例。当前配对码和客户端凭据会立即失效；操作日志仍保留用于审计。", "Permanently delete this instance. Its pairing code and client credential are invalidated immediately; operation logs remain for audit."),run:()=>perform(async()=>{await client.request(base,(value):value is undefined=>value===undefined,{method:"DELETE"})},removed)})}>{t("删除实例", "Delete instance")}</Button></div></section></>}
 {page==="details"&&<section className="sarmg-content-panel" aria-label={t("配置设置", "Configuration settings")}><h2>{t("配置设置", "Configuration settings")}</h2>
 <nav className="sunshine-config-navigation" aria-label={t("Sunshine 配置分类", "Sunshine configuration categories")}>{visibleCategories.map(category=><Button key={category.id} type="button" aria-pressed={activeCategory===category.id} aria-controls={baseline&&fieldDefinitions!==null?`sunshine-config-${category.id}`:undefined} onClick={()=>setConfigCategory(category.id)}>{category.label}</Button>)}</nav>
 <p>{t("受管字段由 管理端 统一管理。本地同时编辑可能发生竞争；修订检查不是 Sunshine 原子并发控制。", "The manager owns managed fields. Local edits may race with remote changes; revision checks are not atomic concurrency control in Sunshine.")}</p>
 <div className="sarmg-actions"><Button disabled={busy||device.revoked||!device.registered||operations.some(operation=>["pending","running"].includes(operation.state)&&operation.action==="sunshine.config.read")} onClick={()=>void submit({kind:"read_config"})}>{t("从 客户端 读取配置", "Read configuration from client")}</Button><Button disabled={!device.snapshot||busy} onClick={loadLatest}>{t("使用最新配置（丢弃未提交编辑）", "Use latest configuration (discard unsaved edits)")}</Button></div>
 {baseline&&device.snapshot&&baseline.revision!==device.snapshot.revision&&<p role="alert">{t("配置修订已变化。请核对最新配置后重新编辑，不能覆盖其他修改。", "The configuration revision has changed. Review the latest configuration and edit again; do not overwrite other changes.")}</p>}
 {baseline&&fieldDefinitions===null?<p>{t("正在加载配置字段定义…", "Loading configuration field definitions…")}</p>:baseline?<form onSubmit={difference} noValidate><p>{t("未列出的配置保留不变；命令、文件路径和敏感网络设置不开放远程修改。", "Unlisted settings are preserved. Commands, file paths and sensitive network settings cannot be changed remotely.")}</p>
 {visibleCategories.map(category=><section key={category.id} id={`sunshine-config-${category.id}`} data-config-category={category.id} hidden={activeCategory!==category.id} aria-label={category.label}>
 <h3>{category.label}</h3>
 {!configFields.some(field=>field.category===category.id)&&<p>{t("当前设备没有可远程修改的此类配置。", "This device has no remotely editable settings in this category.")}</p>}
 {configFields.filter(field=>field.category===category.id).map(field=><div key={field.key} className="sunshine-config-field"><FormField label={field.label}>{field.inputKind==="select"?<select aria-label={field.label} value={draft[field.key]??""} disabled={busy||remove.includes(field.key)} onChange={event=>{setDraft({...draft,[field.key]:event.target.value});setPreview(null)}}><option value="">{t("未显式设置", "Not explicitly set")}</option>{field.options.map(value=><option key={value} value={value}>{configValueLabel(value)}</option>)}</select>:<TextField type={field.inputKind==="integer"?"number":"text"} min={field.minimum} max={field.maximum} step={1} maxLength={field.maximum_length} pattern={field.inputKind==="text"?".{1,32}":undefined} value={draft[field.key]??""} disabled={busy||remove.includes(field.key)} onChange={event=>{setDraft({...draft,[field.key]:event.target.value});setPreview(null)}}/>}</FormField>{field.prerequisite&&<small>{prerequisiteLabel(field.prerequisite)}</small>}
 <label><input type="checkbox" checked={remove.includes(field.key)} disabled={busy||!(field.key in baseline.fields)} onChange={event=>{setRemove(event.target.checked?[...remove,field.key]:remove.filter(key=>key!==field.key));setPreview(null)}}/>{t("恢复默认（删除显式设置）", "Restore default (remove explicit setting)")}</label></div>)}
 </section>)}
 <Button type="submit" disabled={blocked}>{t("预览变更", "Preview changes")}</Button></form>:<p>{t("尚未读取配置。设备注册后可提交读取任务；离线任务会等待连接。", "Configuration has not been read. Submit a read task after registration; offline tasks wait for a connection.")}</p>}
 {preview?.kind==="patch_config"&&<section className="sarmg-content-stack" aria-label={t("变更差异预览", "Change preview")}><h3>{t("变更差异预览", "Change preview")}</h3><table><thead><tr><th>{t("字段", "Field")}</th><th>{t("原值", "Previous value")}</th><th>{t("新值", "New value")}</th></tr></thead><tbody>{[...Object.keys(preview.set),...preview.remove].map(key=><tr key={key}><td>{configFields.find(field=>field.key===key)?.label??key}</td><td>{baseline?.fields[key]===undefined?t("默认", "Default"):configValueLabel(baseline.fields[key])}</td><td>{preview.remove.includes(key)?t("恢复默认", "Restore default"):configValueLabel(String(preview.set[key]))}</td></tr>)}</tbody></table><p>{t("只保存配置，不自动重启。", "Save configuration only; do not restart automatically.")}</p><Button disabled={blocked} onClick={()=>void submit(preview)}>{t("确认保存配置", "Confirm configuration save")}</Button><Button onClick={()=>setPreview(null)}>{t("返回编辑", "Back to editing")}</Button></section>}
 <p>{states[device.configuration_state]}</p><Button disabled={blocked||!device.snapshot||!device.capabilities?.restart_allowed} onClick={()=>setConfirm({title:t("确认重启 Sunshine", "Confirm Sunshine restart"),description:t("重启可能中断正在进行的串流。必须由管理员明确授权；客户端 管理进程保持独立。重启后仍可能需要人工验证运行时生效。", "Restarting may interrupt an active stream and requires explicit administrator authorization. The client remains independent. Runtime effect may still need manual verification after restarting."),run:async()=>{if(device.snapshot)await submit({kind:"restart",expected_revision:device.snapshot.revision,administrator_confirmed:true})}})}>{t("重启 Sunshine", "Restart Sunshine")}</Button>{!device.capabilities?.restart_allowed&&<p>{t("客户端 本机尚未授权受控重启。", "Controlled restarts have not been authorized locally on the client.")}</p>}</section>}
 {page==="details"&&<SunshineControls device={device} operations={operations} busy={busy} blocked={blocked} submit={submit} confirm={setConfirm}/>}
    {page==="logs"&&<section className="sarmg-content-panel"><h2>{t("日志", "Logs")}</h2>{!operations.length&&<p>{t("暂无日志", "No logs yet")}</p>}{operations.map(operation=><article className="sarmg-content-stack" key={operation.operation_id}><h3>{operationLabel(operation.action)} · {tasks[operation.state]}</h3><code>{operation.operation_id}</code>{operation.resolution&&<p>{t("人工结论：", "Manual resolution:")}{operationLabel(operation.resolution)}</p>}{operation.result&&<p>{t("结果：", "Result:")}{operationLabel(operation.result.kind)} {operation.result.reason?operationLabel(operation.result.reason):""}</p>}{operation.result?.kind==="conflict"&&<p role="alert">{t("配置冲突，请重新读取并核对差异。", "Configuration conflict. Read the configuration again and review the differences.")}</p>}{operation.reconciliation&&<p>{t("客户端 核对证据：", "Client reconciliation evidence:")}{operationLabel(operation.reconciliation.kind)} {operation.reconciliation.reason?operationLabel(operation.reconciliation.reason):""}{t("。证据不会自动代替管理员确认。", ". Evidence does not replace administrator confirmation.")}</p>}{operation.state==="unknown"&&<div className="sarmg-actions">{[["confirmed_succeeded",t("确认已成功", "Confirm success")],["confirmed_failed",t("确认未成功", "Confirm failure")],["unable_to_confirm",t("仍无法确认", "Still unable to confirm")]].map(([resolution,label])=><Button key={resolution} disabled={busy} onClick={()=>setConfirm({title:label,description:t("请先核对实际设备状态。此操作只记录人工结论，不会重复执行原操作。", "Check the actual device state first. This records a manual conclusion only; it does not rerun the original operation."),run:()=>perform(async()=>{const updated=await client.request(`${CURRENT_API_PREFIX}/sunshine/operations/${operation.operation_id}/resolve`,isOperation,{method:"POST",body:JSON.stringify({resolution})});operationRevision.current+=1;setOperations(values=>values.map(value=>value.operation_id===updated.operation_id?updated:value))})})}>{label}</Button>)}</div>}</article>)}</section>}
 {confirm&&<ConfirmDangerDialog title={confirm.title} description={confirm.description} pending={busy} onClose={()=>setConfirm(null)} onConfirm={()=>{const action=confirm;setConfirm(null);void action.run()}}/>}
 </div>;
}
